### ISSUE TITLE
Install fails when building ruamel.yaml

### ISSUE THREAD

**Issue by tilmantroester** [LSSTDESC/ceci#15]
Installing ceci through pip is failing on my machine. The error message is

```Collecting ruamel.yaml==0.13.13 (from cwlgen->ceci)
  Using cached https://files.pythonhosted.org/packages/d9/2d/f1773b60c7a78a832f6068761167907302927cb6c7279275a0dcee102e05/ruamel.yaml-0.13.13.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/5g/5ynbyz2528vfyfpjw7spc5fc0000gn/T/tmp_ruamel_q8ni772l/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/5g/5ynbyz2528vfyfpjw7spc5fc0000gn/T/tmp_ruamel_q8ni772l/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/5g/5ynbyz2528vfyfpjw7spc5fc0000gn/T/tmp_ruamel_q8ni772l/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/5g/5ynbyz2528vfyfpjw7spc5fc0000gn/T/pip-install-wnsl8fb8/ruamel.yaml/setup.py", line 854, in <module>
        main()
      File "/private/var/folders/5g/5ynbyz2528vfyfpjw7spc5fc0000gn/T/pip-install-wnsl8fb8/ruamel.yaml/setup.py", line 843, in main
        setup(**kw)
      File "/Users/yooken/Codes/miniconda/envs/tjpcosmo/lib/python3.7/site-packages/setuptools/__init__.py", line 129, in setup
        return distutils.core.setup(**attrs)
      File "/Users/yooken/Codes/miniconda/envs/tjpcosmo/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/yooken/Codes/miniconda/envs/tjpcosmo/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/Users/yooken/Codes/miniconda/envs/tjpcosmo/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/Users/yooken/Codes/miniconda/envs/tjpcosmo/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/Users/yooken/Codes/miniconda/envs/tjpcosmo/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable

```

I've tried a number of different pyyaml installations (3.13, 4.2) but this doesn't seem to have an effect. Python version is 3.7.
Installing from `master` with `python setup.py install` fails as well at the `ruamel.yaml` step.

**Comment by joezuntz** [comment]
Could also try doing this first:
```
pip install --upgrade pip setuptools
```

and then see if this works on its own:
```
pip install ruamel.yaml
```
?

**Comment by tilmantroester** [comment]
Installing `ruamel.yaml` by itself works but it installs a version that is incompatible with cwlgen:
`cwlgen 0.2.8 has requirement ruamel.yaml==0.13.13, but you'll have ruamel-yaml 0.15.44 which is incompatible.`
Installing `ruamel.yaml==0.13.13` gives the same error as before.

**Comment by EiffL** [comment]
Thanks Tilman for reporting that, I'll fix this issue

**Comment by joezuntz** [comment]
Hopefully fixed now
